Update iterator.hpp
u123262/cxx-tasks pull request #2
Opened 2018-10-19 09:45 UTC by u123262

```
0.000 s: iterator::copy_from_vector
0.001 s: iterator::copy_to_vector
0.000 s: begin/end
0.001 s: iterator::operations
0.001 s: prefix
0.002 s: iterator::operations
0.003 s: postfix
0.003 s: iterator::operations
0.001 s: advance::length
0.002 s: iterator::operations
0.000 s: advance: delta < width
0.001 s: iterator::operations
0.000 s: advance: delta > width
0.000 s: iterator::operations
0.000 s: distance
0.001 s: iterator::operations
0.000 s: iterator::write
===============================================================================
All tests passed (15 assertions in 4 test cases)
```

2018-10-19 17:02 UTC, igsha requested changes
В принципе, тесты все проходят, но я нашёл одно критичное замечание.

2018-10-19 17:02 UTC, igsha commented on iterator/include/iterator.hpp
> +    void deccrement()
здесь точно всё правильно с именем?

2018-10-19 17:02 UTC, igsha commented on iterator/include/iterator.hpp
> +            increment();
логичнее сделать наоборот: `advance` на любой шаг, а `increment` и `decrement` перевызов `advance(+/-1)` (или даже вообще не реализовывать, так как это решение по умолчанию наследуется)

2018-10-19 17:02 UTC, igsha commented on iterator/include/iterator.hpp
> +        return (i.base() - this->base() - tmp);
Я не разобрался с формулой. Например:
```
i.base() = b + s
this->base() = b + w - 1
```
т.е., один итератор - это начало следующей строки, с предыдущий стоит на последнем элементе предыдущей строки. Далее подставляю:
<img src="https://latex.codecogs.com/gif.latex?s&space;-&space;(w&space;-1)&space;-&space;\left[&space;\frac{s-(w-1)}{s-1}&space;\right&space;]&space;(s-w)=&space;s&space;-&space;w&space;&plus;&space;1&space;-&space;0\cdot(s-w)&space;=&space;s-w&plus;1&space;=&space;\delta&space;&plus;&space;1" title="s - (w -1) - \left[ \frac{s-(w-1)}{s-1} \right ] (s-w)= s - w + 1 - 0\cdot(s-w) = s-w+1 = \delta + 1" />
У меня получилось, что разница не равна 1, хотя должна быть.

2018-10-22 19:06 UTC, igsha requested changes

2018-10-22 19:06 UTC, igsha commented on iterator/include/iterator.hpp
> +        for (int j = i.i; j < i.i - (int)(i.base() - this->base()); j++) {
Хмм... слишком сложно. Я не могу выделить "формулу", по которой был написан код.

По сути здесь должны быть рассуждения о двумерных координатах.
Это частный случай задачи линеаризации [многомерных координат](https://cvlabmiet.github.io/interview-tasks/#id9).
Наша задача вычислить разницу двух линеаризованных координат с изменения базиса из `{1, stride}` в `{1, width}`.
Двумерная координата у нас записывается как `base() = b + r*stride + i`, где `r` и `b` нам неизвестны, зато известен `base()`.
Для вычисления разницы между двумя координатами `b` не нужно знать, так как она совпадает для обоих координат.

Пусть нам необходимо вычислить разность между `x0` и `x1`:
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{aligned}&space;x_0&space;&=&space;r_0&space;w&space;&plus;&space;c_0&space;\\&space;x_1&space;&=&space;r_1&space;w&space;&plus;&space;c_1&space;\\&space;\delta&space;&=&space;x_1&space;-&space;x_0&space;=&space;(r_1&space;-&space;r_0)&space;w&space;&plus;&space;(c_1&space;-&space;c_0)&space;\end{aligned}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{aligned}&space;x_0&space;&=&space;r_0&space;w&space;&plus;&space;c_0&space;\\&space;x_1&space;&=&space;r_1&space;w&space;&plus;&space;c_1&space;\\&space;\delta&space;&=&space;x_1&space;-&space;x_0&space;=&space;(r_1&space;-&space;r_0)&space;w&space;&plus;&space;(c_1&space;-&space;c_0)&space;\end{aligned}" title="\begin{aligned} x_0 &= r_0 w + c_0 \\ x_1 &= r_1 w + c_1 \\ \delta &= x_1 - x_0 = (r_1 - r_0) w + (c_1 - c_0) \end{aligned}" /></a>

Но у нас вместо `w` (width) использован `s` (stride). Как быть?
Просто вычислим разность как она есть:
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{aligned}&space;\delta'&space;&=&space;x_1'&space;-&space;x_0'&space;=&space;(r_1&space;-&space;r_0)&space;s&space;&plus;&space;(c_1&space;-&space;c_0)&space;\\&space;r_1&space;-&space;r_0&space;&=&space;\left[&space;\frac{\delta'}{s}&space;\right&space;]&space;\\&space;c_1&space;-&space;c_0&space;&=&space;\delta'&space;\mod&space;s&space;\end{aligned}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{aligned}&space;\delta'&space;&=&space;x_1'&space;-&space;x_0'&space;=&space;(r_1&space;-&space;r_0)&space;s&space;&plus;&space;(c_1&space;-&space;c_0)&space;\\&space;r_1&space;-&space;r_0&space;&=&space;\left[&space;\frac{\delta'}{s}&space;\right&space;]&space;\\&space;c_1&space;-&space;c_0&space;&=&space;\delta'&space;\mod&space;s&space;\end{aligned}" title="\begin{aligned} \delta' &= x_1' - x_0' = (r_1 - r_0) s + (c_1 - c_0) \\ r_1 - r_0 &= \left[ \frac{\delta'}{s} \right ] \\ c_1 - c_0 &= \delta' \mod s \end{aligned}" /></a>

Дальше, я надеюсь, Вы уже справитесь. В итоге функция превращается просто в одну строчку.

2018-10-23 10:03 UTC, u123262 commented
@igsha 

```
ptrdiff_t distance_to( image_iterator const & element ) const
    {
        int delta = element.base() - this->base();
        int offset = (element.i % (int)stride_) * (delta > 0 ? 1:-1);
        delta = delta + offset;

        return delta / (int)stride_ * (int)width_ + delta % (int)stride_ - offset;
    }
```
Добавил смещение для учета изначальной позиции элемента в строке. 
Без смещения не будет проходить тест "next row", т.к. вычисление расстояния будет начинаться с начала строки.

2018-10-23 17:36 UTC, igsha commented
@u123262, и всё-таки я нашёл ещё пример, когда предложенный способ не сработает:
```cpp
CHECK(distance(it + 128, it + 127) == -1);
```

2018-10-23 17:36 UTC, igsha commented on iterator/include/iterator.hpp
> +            increment();
@u123262, здесь будут какие-то изменения/комментарии?

2018-10-23 18:32 UTC, u123262 commented
@igsha 

```
int delta = element.base() - this->base();
int sign = delta > 0 ? 1:-1;
int offset = delta > 0 ? i:element.i % (int)stride_;

delta = abs(delta) + offset;

return (delta / (int)stride_ * (int)width_ + delta % (int)stride_ - offset)*sign;
```

2018-10-25 14:33 UTC, u123262 reviewed
ptrdiff_t distance_to( image_iterator const & element ) const

2018-10-25 14:33 UTC, u123262 commented on iterator/include/iterator.hpp
> +    ptrdiff_t distance_to( image_iterator const & i ) const
Переписал функцию distance_to, предыдущая реализация работала корректно не во всех случаях.

2018-10-25 14:36 UTC, u123262 commented
```
ptrdiff_t distance_to( image_iterator const & element ) const
    {
        int delta = element.base() - this->base();
        int sign = delta > 0 ? 1:-1;
        int offset = delta > 0 ? i:element.i % (int)stride_;

        delta = abs(delta) + offset;

        return (delta / (int)stride_ * (int)width_ + delta % (int)stride_ - offset)*sign;
    }
```

2018-10-25 16:23 UTC, igsha commented
u123262, ок, вижу обновления в `distance_to`. Так как тесты проходят, исправления принимаются. Но что насчёт вопроса по поводу `advance`? Мне ждать какие-то исправления?

2018-10-25 16:27 UTC, u123262 commented
@igsha да, в ближайшее время исправлю.

2018-10-26 17:46 UTC, u123262 commented
@igsha исправление `advance`

2018-10-27 06:49 UTC, igsha approved these changes

2018-10-27 06:51 UTC, merged