Update proxy.hpp
u123262/cxx-tasks pull request #3
Opened 2018-10-19 09:47 UTC by u123262

```
0.000 s: proxy::access
1.016 s: proxy::threadsafe
===============================================================================
All tests passed (23 assertions in 2 test cases)
```

2018-10-19 17:16 UTC, igsha requested changes
В принципе, задача решена. Можем сойтись на 10-ти баллах, так как есть недочёт. Сумма сейчас несгораемая. Т.е., можно будет повысить баллы в задаче в любое время в течение семестра.

На этой неделе в оценку войдёт та лабораторная, которая получит наибольшее количество баллов.

2018-10-19 17:16 UTC, igsha commented on proxy/include/proxy.hpp
> +        std::mutex* mutex_;
Необходимо использовать RAII подход. Т.е., в идеале здесь не должно быть поля `mutex_`.  
Я оставлю эту [ссылку](https://en.cppreference.com/w/cpp/thread/lock_guard) здесь.

2018-10-22 17:36 UTC, igsha requested changes

2018-10-22 17:36 UTC, igsha commented on proxy/include/proxy.hpp
> +    class proxy: private T
Вот тут не порядок: если `T` будет `int`, то код не скомпилируется. Здесь можно вообще не наследоваться.

2018-10-22 17:36 UTC, igsha commented on proxy/include/proxy.hpp
> +        proxy (T* ptr, std::unique_lock<std::mutex> lk) :ptr_ (ptr), lk_(std::move(lk)) { }
нет, это не RAII, так как в конструктор передаётся **уже** залоченный объект.

2018-10-22 17:36 UTC, igsha commented on proxy/include/proxy.hpp
> +        ~proxy() { }
деструктор пустой => деструктор не нужен

2018-10-26 18:01 UTC, u123262 reviewed
@igsha std::lock_guard при инициализации.

2018-10-26 18:01 UTC, u123262 commented on proxy/include/proxy.hpp
> +        std::unique_lock<std::mutex> lck(mutex_);
std::unique_lock

2018-10-27 06:54 UTC, igsha approved these changes

2018-10-27 06:54 UTC, merged