Update variant.hpp
u123262/cxx-tasks pull request #4
Opened 2018-11-06 20:13 UTC by u123262

```
0.000 s: variant::array
0.000 s: variant::number
0.000 s: variant::recursive_array
0.000 s: variant::recursive_array2
0.000 s: std::get
0.001 s: variant::recursive_map
0.000 s: as
0.001 s: variant::recursive_map
===============================================================================
All tests passed (19 assertions in 5 test cases)
```

2018-11-07 05:37 UTC, igsha requested changes
Требуются доработки

2018-11-07 05:37 UTC, igsha commented on variant/include/variant.hpp
> +    number(const T& x):std::variant<int, float>(x) {};
зачем здесь шаблонный параметр?

2018-11-07 05:37 UTC, igsha commented on variant/include/variant.hpp
> +    array(std::initializer_list<number> x):std::vector<number>(x) {};
слишком сложно, можно просто `using vector::vector;`

2018-11-07 05:37 UTC, igsha commented on variant/include/variant.hpp
> +    recursive_array(std::initializer_list<std::variant<number, std::shared_ptr<recursive_array>>> x):
см. предыдущий комментарий

2018-11-07 05:37 UTC, igsha commented on variant/include/variant.hpp
> +    auto convert(const std::initializer_list<std::variant<number, recursive_array2>>& input){
слишком сложно. `using vector::vector;` решит все проблемы, так как будет неявно вызван конвертирующий конструктор (из `recursive_array2` в `boost::recursive_wrapper<recursive_arra2>`)

2018-11-07 05:37 UTC, igsha commented on variant/include/variant.hpp
> +	std::enable_if_t<!std::is_same<T, struct recursive_map>::value, T>
`enable_if` уже в прошлом. Для реализации SFINAE используйте `if constexpr` и `std::disjunction_v`

2018-11-07 07:38 UTC, u123262 commented
@igsha исправил

2018-11-07 16:29 UTC, igsha requested changes
Надо сделать `git rebase`. Перед этим ещё можно синхронизироваться с апстримом:
```
git remote add upstream https://github.com/cvlabmiet/cxx-tasks
git fetch upstream
git rebase upstream/master
```

2018-11-07 16:29 UTC, igsha commented on variant/include/variant.hpp
> +        if constexpr (std::conjunction_v<std::is_same<T, struct recursive_map>>) {
Ну, если так, тогда `std::conjunction_v` тут ни к чему

2018-11-07 16:29 UTC, igsha commented on variant/include/variant.hpp
> +    auto as() {
Я одновил тесты, теперь там более серьёзнее проверяется. В такой реализации, кстати, будет ненужная копия объекта T

2018-11-07 20:25 UTC, u123262 commented
@igsha исправил

2018-11-08 05:37 UTC, igsha requested changes
Не собирается

2018-11-08 05:37 UTC, igsha commented on variant/include/variant.hpp
> +			return std::get<boost::recursive_wrapper< recursive_map >>(*this).get();
это какой-то костыль: почему здесь `recursive_map`? У меня из-за этого не собирается ничего.

2018-11-08 05:37 UTC, igsha commented on variant/include/variant.hpp
> +	using base::base;
Тут везде можно писать проще: `using unordered_map::unordered_map`, так как область видимости расширяется при наследовании. Указание всех типов для `unordered_map` не требуется, так как сам класс `recursive_map` не шаблонный, следовательно, `unordered_map` не зависит от неопределённого шаблонного типа. В лекциях я про использование `using` касался немного.

2018-11-08 05:58 UTC, u123262 commented
@igsha исправил

2018-11-11 06:50 UTC, igsha requested changes
`variant_decorator` не должен зависеть от `recursive_map`

2018-11-11 06:50 UTC, igsha commented on variant/include/variant.hpp
> +			return std::get<boost::recursive_wrapper< recursive_map >>(*this).get();
@u123262, а с этим что? Почему `variant_decorator` зависит от какого-то несвязанного типа `recursive_map`? Логичнее сделать наоборот: если никакого подходящего типа не нашли, значит, он завёрнут в `boost::recursive_wrapper`: `std::get<boost::recursive_wrapper<T>>(*this)`

2018-11-13 14:52 UTC, u123262 commented
@igsha использовал `std::disjunction_v`

2018-11-13 14:58 UTC, igsha approved these changes

2018-11-13 14:58 UTC, merged