Update type_map.hpp
u123262/cxx-tasks pull request #5
Opened 2018-11-06 20:14 UTC by u123262

```
0.000 s: type_map::enum
0.000 s: type_map::int
===============================================================================
All tests passed (7 assertions in 2 test cases)
```

2018-11-07 17:59 UTC, igsha requested changes
Требуется обновить ветку относительно апстрима и дописать функцию.

2018-11-07 17:59 UTC, igsha commented on type_map/include/type_map.hpp
> +    const auto& as() const
вышло обновление, надо ещё реализовать неконстантный `as`

2018-11-07 20:25 UTC, u123262 commented
@igsha исправил

2018-11-08 05:05 UTC, igsha commented on type_map/include/type_map.hpp
> +    auto& get(TypeMap& tm)
nitpick: вообще, это можно было бы одной функцией сделать. На досуге можно подумать. На оценку это не влияет.

2018-11-08 05:07 UTC, merged