Parser
u123262/cxx-tasks pull request #7
Opened 2018-11-18 15:23 UTC by u123262

CSV:

```
0.000 s: csv::cell
0.000 s: csv::csv
0.000 s: csv::operator_csv
0.000 s: csv::row
0.000 s: csv::string
===============================================================================
All tests passed (15 assertions in 5 test cases)
```

JSON:

```
0.000 s: the same type
0.001 s: json::array
0.000 s: different types
0.001 s: json::array
0.000 s: self type
0.001 s: json::array
0.000 s: root is object
0.000 s: json::json
0.000 s: root is array
0.000 s: json::json
0.000 s: json::nullable
0.000 s: json::number
0.000 s: different types
0.000 s: json::object
0.000 s: recursion
0.001 s: json::object
0.000 s: json::operator_json
===============================================================================
All tests passed (40 assertions in 6 test cases)
```

QUOTED_STRING:
```
0.000 s: quoted_string::comma
0.000 s: quoted_string::failure
0.000 s: quoted_string::newline

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests_parser.exe is a Catch v2.4.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
quoted_string::quote
-------------------------------------------------------------------------------
C:\Users\Shipitsyn\Desktop\CXX\parser\tests\quoted_string.cpp(32)
...............................................................................

C:\Users\Shipitsyn\Desktop\CXX\parser\tests\quoted_string.cpp(32): FAILED:
due to unexpected exception with message:
  Trailing symbols, difference: 8

0.000 s: quoted_string::quote
0.000 s: quoted_string::spaces
===============================================================================
test cases: 5 | 4 passed | 1 failed as expected
assertions: 7 | 6 passed | 1 failed as expected
```

VARIANT_DECORATOR:
```
0.000 s: variant_decorator::as
0.000 s: variant_decorator::const
0.000 s: operator=
0.001 s: variant_decorator::constructors
0.000 s: copy constructor
0.001 s: variant_decorator::constructors
===============================================================================
All tests passed (7 assertions in 3 test cases)
```

2018-11-18 16:08 UTC, igsha requested changes
Требуются мелкие доработки. Есть один необязательный тест. Постарайтесь его добить

2018-11-18 16:08 UTC, igsha commented on parser/include/csv.hpp
> +                = cell >> *(',' >> cell) >> x3::no_skip['\n'];
здесь можно использовать оператор `%`

2018-11-18 16:08 UTC, igsha commented on parser/include/csv.hpp
> +                 = row >> *row;
а зачем тут ещё один `row`? Если хочется хотя бы один получить, тогда достаточно использовать `+` вместо `*`

2018-11-18 16:08 UTC, igsha commented on parser/include/json.hpp
> +        auto const array_def = '[' >> value >> *(',' >> value) >> ']';
здесь тоже ничего не мешает использовать оператор `%`

2018-11-18 16:08 UTC, igsha commented on parser/include/quoted_string.hpp
> +    auto const quoted_string = '"' >> x3::no_skip[*(x3::char_ - '"')] >> '"';
а как быть с комбинацией `\"`?

2018-11-19 10:05 UTC, u123262 commented
@igsha исправил

2018-11-19 10:07 UTC, igsha approved these changes

2018-11-19 10:08 UTC, merged